# Book settings
title                       : Reproduce LIGO # The title of the book. Will be placed in the left navbar.
author                      : Ligo Scientific Collaboration (LSC) and Minji Park # The author of the book
logo                        : logo.png  # A path to the book logo

execute:
  execute_notebooks: 'off'

only_build_toc_files: true

# TODO: the below should be disabled and instead the sphinx section activated
# after we upgrade to j-book newer than 0.9.1 and its dependencies.  For now
# this gives us the equivalent of html_images fixes, but without version
# conflicts that currently arise from trying to use it.
#parse:
#  myst_extended_syntax: true

# Sphinx section commented out for now as per above todo, will activate it
# later. 

bibtex_bibfiles: 
  - references.bib

sphinx:
  config:
    exclude_patterns:
      - README.md
    myst_enable_extensions: 
    - amsmath
    - dollarmath
    - html_image
    - html_admonition